language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t silviocifone/docker-react:latest -f Dockerfile.dev . 

script:
  - docker run -e CI=true silviocifone/docker-react npm run test